### GENERAL SETTINGS ###

# Site settings
title: IQ-TREE
description: "IQ-TREE: Efficient phylogenetic software by maximum likelihood"
analytics: UA-38693379-1
baseurl: "/IQ-TREE" #important: start with /
url: "http://cibiv.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url:
  - title: google
    url:
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 
    - Center for Integrative Bioinformatics Vienna
    - University of Vienna
email: minh.bui(at)univie.ac.at


### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Bui Quang Minh
    position: Team leader
    text: Design IQ-TREE core, ultrafast bootstrap and model selection. 
    img: jule.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~minh
  - name: Lam Tung Nguyen
    position: Developer
    text: Design IQ-TREE search algorithm.
    img: jule.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~tung
  - name: Olga Chernomor
    position: Developer
    text: Design partition models and terrace-aware tree search.
    img: jule.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~olga
  - name: Heiko A. Schmidt
    position: Developer
    text: Implement <a href="http://www.tree-puzzle.de">TREE-PUZZLE</a> features into IQ-TREE.
    img: jule.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~hschmidt
  - name: Jana Trifinopoulos
    position: Developer
    text: Design and maintain IQ-TREE web service.
    img: jule.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~jana
  - name: Arndt von Haeseler
    position: Advisor
    text: Consultant, inspiring ideas and financial support.
    img: jule.jpg
    social:
      - title: envelope #use for email address
        url: http://www.cibiv.at/~haeseler

    
# Clients information. Shown on Home and About pages.
#clients:
#  - name: Vimeo
#    img: client03.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "IQ-TREE is developed at <a href='http://www.cibiv.at'>CIBIV</a> by <a href='/about/'>IQ-TREE development team</a>."

# Testimonial content. Shown on Home and About page. 
#testimonial:
#    message: "Helo."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO
    
