### GENERAL SETTINGS ###

# Site settings
title: IQ-TREE
description: "IQ-TREE: Efficient phylogenetic software by maximum likelihood"
analytics: UA-38693379-1
baseurl: "" #important: start with /
url: "http://www.iqtree.org"

# Build settings
markdown: kramdown
kramdown:
  enable_coderay: true
  syntax_highlighter: coderay
  syntax_highlighter_opts: { line_numbers: false }

permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#337ab7" #"#F70031" 
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"
  
  
### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: https://github.com/Cibiv/IQ-TREE

twitter_username: bq_minh
    
# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines: 

email: minh.bui(at)univie.ac.at

links:
  - <a href="http://www.cibiv.at">Center for Integrative Bioinformatics Vienna</a>
  - <a href="https://www.univie.ac.at">University of Vienna</a>
  - <a href="http://www.fwf.ac.at/">Austrian Science Fund</a>

supports:
  - <a href="https://groups.google.com/d/forum/iqtree">IQ-TREE Google group</a>

### GENERAL DATA FOR VARIOUS LOCATIONS ###
    
# Members information. Shown on About page.
members:
  - name: Lam Tung Nguyen
    position:
    text: Tree search algorithm and parallelization.
    img: tung.jpg
    gscholar: https://scholar.google.com/citations?user=TQx3GV8AAAAJ
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~tung
  - name: Olga Chernomor
    position:
    text: Partition models and phylogenomic search.
    img: olga.jpg
    gscholar: https://scholar.google.com/citations?user=28f0gdQAAAAJ
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~olga
  - name: Heiko A. Schmidt
    position:
    text: Integration of <a href="http://www.tree-puzzle.de">TREE-PUZZLE</a> features.
    img: hschmidt.png
    gscholar: https://scholar.google.com/citations?user=8lFCw7IAAAAJ
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~hschmidt
  - name: Jana Trifinopoulos
    position:
    text: W-IQ-TREE web service.
    img: jana.jpg
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~jana
  - name: Bui Quang Minh
    position:
    text: Team leader, software core, ultrafast bootstrap, model selection.
    img: minh.jpg
    gscholar: https://scholar.google.com/citations?user=UI0xN_QAAAAJ
    social:
      - title: home #use for email address
        url: http://www.cibiv.at/~minh
      - title: university
        url: https://scholar.google.com/citations?user=UI0xN_QAAAAJ
  - name: Dominik Schrempf
    position:
    text: Polymorphism-aware models (PoMo).
    img: dominiks.jpg
    gscholar: https://scholar.google.com/citations?user=3pvnGAcAAAAJ
    social:
      - title: home #use for email address
        #url: http://i122server.vu-wien.ac.at/pop/lab_members/Dominik_Schrempf.html
        url: https://dschrempf.github.io
  - name: Michael Woodhams
    position:
    text: Lie Markov models.
    img: woodhams.jpg
    gscholar: https://scholar.google.com/citations?user=brh1wEkAAAAJ
    social:
      - title: home #use for email address
        url: http://www.utas.edu.au/profiles/staff/maths-physics/michael-woodhams
  - name: Arndt von Haeseler
    position:
    text: Advice, ideas and financial support.
    img: arndt.jpg
    gscholar: https://scholar.google.com/citations?user=XqglmcgAAAAJ
    social:
      - title: envelope #use for email address
        url: http://www.cibiv.at/~haeseler

    
# Clients information. Shown on Home and About pages.
#clients:
#  - name: Vimeo
#    img: client03.png
    
# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: IQ-TREE code is hosted at <a href="https://github.com/Cibiv/IQ-TREE">GitHub repository</a>.

# Testimonial content. Shown on Home and About page. 
#testimonial:
#    message: "Helo."
#    author: Marcel Newman
#    position: WEB DESIGNER - BLACKTIE.CO
    
#gems: [jekyll-paginate]
#paginate: 10
#paginate_path: "/blog/page:num/"
num_pages: 4

compress_html:
  clippings: all
  comments: all
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: []
